version: 0.2
phases:
  install:
    commands:
  build:
    commands:
      - echo "Deploying DAGs to S3"
      - aws s3 sync ./dags/WORKDAYFINA s3://airflow-dags-production-bucket-new/dags/WORKDAYFINA --exact-timestamps
      - aws s3 sync ./dags/MX-DERIVATIVES s3://airflow-dags-production-bucket-new/dags/MX-DERIVATIVES --exact-timestamps
      
