version: 0.2
phases:
  install:
    commands:
  pre_build:
    commands:
  post_build:
    commands:
      - echo "Deploying DAGs to S3"
      - aws s3 sync ./dags s3://airflow-dags-production-bucket-new/dags/WORKDAYFINA --exact-timestamps
artifacts:
  files:
    - dags/*
  discard-paths: yes
