version: 0.2
phases:
  install:
    commands:
      - apt-get update && apt-get install -y libsasl2-dev
      - pip install -r requirements.txt  # Install dependencies
  pre_build:
    commands:
  build:
    commands:
artifacts:
  files:
    - dags/*
  discard-paths: yes
